userName = input("Enter your Name : \n").upper()
userComment = input("Enter your comment: \n")
openComment = open('comment.txt','a')
openComment.write( '~'+ userName + '~ \n')
openComment.write(userComment + '\n')
openComment.close()
readComment = open("comment.txt",'r').read()
print("Comments are here!! : \n")
print(readComment)
print('\n')
